server:
  port: 8888

spring:
  datasource:
    url:  jdbc:mysql://172.17.0.2:3306/emrysblog?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: cn.emrys.springboot.entity
